baseURL: "https://blog.loikein.one/"
canonifyURLs: true
hasCJKLanguage: true
DefaultContentLanguage: zh
languageCode: zh-Hans
publishDir: public

title: 此生未命名
copyright: CC BY-NC loikein 2023
theme: diary

markup:
  highlight:
    codeFences: true
    guessSyntax: true
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: false
    # https://xyproto.github.io/splash/docs/longer/all.html
    tabWidth: 4
  goldmark:
    renderer:
      unsafe: true
    extensions:
      definitionList: true

ignoreFiles:
  - blog-*.xml$
ignoreErrors: 
  - "error-remote-getjson"

params:
  title: "此生未命名／Untitled Life"
  subtitle: "用爱和理性对抗荒谬"
  enableGitalk: false
  enableOpenGraph: true
  enableTwitterCards: true
  disableAutoCollapse: true
  description: "一个无趣的人的无趣的博客。"
  customCSS: true
  customJS: true
  favicon: "./favicon.ico"
  touchicon: "./touch-icon.png"
  disqusShortname: loikein-blogspot
  # gitalk:
  #   owner: user
  #   repo: repo name
  #   client_id: your client id
  #   client_secret: your client secret

taxonomies:
  tag: tags
  category: categories
  series: series

menu:
  main:
    - url: /about/
      name: 关于／About
      weight: 1
    - url: /archives/posts/
      name: 归档／Archive
      weight: 2
    - name: 搜索／Search
      url: "https://www.ecosia.org/search?q=site%3Ablog.loikein.one"
      weight: 3
    # - url: /tags/
    #   name: 标签／Tags
    #   weight: 3
    # - url: /categories/
    #   name: 分类／Categories
    #   weight: 4
    - url: /toolbox/
      name: 工具箱／Toolbox
      weight: 5
    - url: /projects/
      name: 个人项目／Projects
      weight: 8
    - url: /changelog/
      name: 更新履历／Changelog
      weight: 9
    - url: /rss/
      name: 订阅／RSS
      weight: 10


privacy:
  disqus:
    disable: false
  googleAnalytics:
    anonymizeIP: true
    disable: false
    respectDoNotTrack: true
    useSessionStorage: true
  instagram:
    disable: false
    simple: true
  twitter:
    disable: false
    enableDNT: true
    simple: true
  vimeo:
    disable: false
    enableDNT: true
    simple: true
  youtube:
    disable: false
    privacyEnhanced: true
