[build]
  command = "hugo --gc --minify -b $URL"
  publish = "/public/"

[build.environment]
  HUGO_VERSION = "0.83.1"
  HUGO_ENABLEGITINFO = "true"

[context.production.environment]
  HUGO_ENV = "production"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
